from pathlib import Path

path = Path('app/src/main/java/com/wavelength/music/ui/nowplaying/NowPlayingScreen.kt')
text = path.read_text()


def replace_once(old: str, new: str):
    global text
    if old not in text:
        raise SystemExit(f'Pattern not found: {old[:160]!r}')
    text = text.replace(old, new, 1)

replace_once(
'''import android.graphics.drawable.BitmapDrawable\nimport androidx.activity.compose.rememberLauncherForActivityResult''',
'''import android.graphics.drawable.BitmapDrawable\nimport android.hardware.Sensor\nimport android.hardware.SensorEvent\nimport android.hardware.SensorEventListener\nimport android.hardware.SensorManager\nimport android.os.SystemClock\nimport androidx.activity.compose.rememberLauncherForActivityResult'''
)

replace_once(
'''    // Subtle 3D parallax: a slow, premium floating tilt rather than a distracting wobble.\n    val parallaxPhase = remember { Animatable(0f) }\n    LaunchedEffect(parallaxAlbumArt, state.isPlaying) {\n        if (parallaxAlbumArt && state.isPlaying) {\n            while (true) {\n                parallaxPhase.animateTo(\n                    1f,\n                    animationSpec = tween(durationMillis = 1700, easing = LinearEasing)\n                )\n                parallaxPhase.animateTo(\n                    -1f,\n                    animationSpec = tween(durationMillis = 1700, easing = LinearEasing)\n                )\n            }\n        } else {\n            parallaxPhase.animateTo(0f, animationSpec = tween(220))\n        }\n    }\n\n    // Neat beat-bounce style: compact pulse with a soft spring return while music is playing.\n    val beatBounceScale = remember { Animatable(1f) }\n    LaunchedEffect(beatBounceAlbumArt, state.isPlaying) {\n        if (beatBounceAlbumArt && state.isPlaying) {\n            while (true) {\n                beatBounceScale.animateTo(\n                    1.065f,\n                    animationSpec = tween(durationMillis = 115, easing = LinearEasing)\n                )\n                beatBounceScale.animateTo(\n                    1f,\n                    animationSpec = spring(\n                        dampingRatio = Spring.DampingRatioMediumBouncy,\n                        stiffness = Spring.StiffnessMedium\n                    )\n                )\n                kotlinx.coroutines.delay(300)\n            }\n        } else {\n            beatBounceScale.animateTo(1f, animationSpec = tween(180))\n        }\n    }\n''',
'''    // Real sensor-driven parallax. Prefer the gravity sensor (stable, already filtered by\n    // Android), then fall back to the accelerometer on devices without TYPE_GRAVITY.\n    var sensorTiltX by remember { mutableFloatStateOf(0f) }\n    var sensorTiltY by remember { mutableFloatStateOf(0f) }\n    DisposableEffect(parallaxAlbumArt, context) {\n        val sensorManager = context.getSystemService(android.content.Context.SENSOR_SERVICE) as SensorManager\n        val motionSensor = sensorManager.getDefaultSensor(Sensor.TYPE_GRAVITY)\n            ?: sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER)\n        val listener = object : SensorEventListener {\n            private var filteredX = 0f\n            private var filteredY = 0f\n\n            override fun onSensorChanged(event: SensorEvent) {\n                if (!parallaxAlbumArt || event.values.size < 2) return\n                // Normalize gravity to roughly -1..1 and low-pass it so the art follows the\n                // phone naturally without jittering from tiny hand movements.\n                val nx = (event.values[0] / 9.81f).coerceIn(-1f, 1f)\n                val ny = (event.values[1] / 9.81f).coerceIn(-1f, 1f)\n                filteredX += (nx - filteredX) * 0.16f\n                filteredY += (ny - filteredY) * 0.16f\n                sensorTiltX = filteredX\n                sensorTiltY = filteredY\n            }\n\n            override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) = Unit\n        }\n\n        if (parallaxAlbumArt && motionSensor != null) {\n            sensorManager.registerListener(listener, motionSensor, SensorManager.SENSOR_DELAY_GAME)\n        }\n        onDispose {\n            sensorManager.unregisterListener(listener)\n            sensorTiltX = 0f\n            sensorTiltY = 0f\n        }\n    }\n\n    // Scale is animated only when the live audio detector below reports a real transient.\n    val beatBounceScale = remember { Animatable(1f) }\n    var beatPulseSequence by remember { mutableStateOf(0L) }\n    LaunchedEffect(beatPulseSequence, beatBounceAlbumArt, state.isPlaying) {\n        if (beatBounceAlbumArt && state.isPlaying && beatPulseSequence > 0L) {\n            beatBounceScale.snapTo(1f)\n            beatBounceScale.animateTo(\n                1.085f,\n                animationSpec = tween(durationMillis = 70, easing = LinearEasing)\n            )\n            beatBounceScale.animateTo(\n                1f,\n                animationSpec = spring(\n                    dampingRatio = Spring.DampingRatioMediumBouncy,\n                    stiffness = Spring.StiffnessHigh\n                )\n            )\n        } else if (!beatBounceAlbumArt || !state.isPlaying) {\n            beatBounceScale.animateTo(1f, animationSpec = tween(140))\n        }\n    }\n'''
)

replace_once(
'''    LaunchedEffect(audioVisualizerEnabled, hasRecordAudioPermission) {\n        if (audioVisualizerEnabled && !hasRecordAudioPermission) {\n            recordAudioPermissionLauncher.launch(Manifest.permission.RECORD_AUDIO)\n        }\n    }\n    val visualizerWaveform by viewModel.visualizerWaveform.collectAsStateWithLifecycle()\n    DisposableEffect(audioVisualizerEnabled, hasRecordAudioPermission) {\n        viewModel.setVisualizerCaptureEnabled(audioVisualizerEnabled && hasRecordAudioPermission)\n        onDispose { viewModel.setVisualizerCaptureEnabled(false) }\n    }\n''',
'''    val needsAudioCapture = audioVisualizerEnabled || beatBounceAlbumArt\n    LaunchedEffect(needsAudioCapture, hasRecordAudioPermission) {\n        if (needsAudioCapture && !hasRecordAudioPermission) {\n            recordAudioPermissionLauncher.launch(Manifest.permission.RECORD_AUDIO)\n        }\n    }\n    val visualizerWaveform by viewModel.visualizerWaveform.collectAsStateWithLifecycle()\n    DisposableEffect(needsAudioCapture, hasRecordAudioPermission) {\n        viewModel.setVisualizerCaptureEnabled(needsAudioCapture && hasRecordAudioPermission)\n        onDispose { viewModel.setVisualizerCaptureEnabled(false) }\n    }\n\n    // Real beat detection from the currently playing audio. Visualizer waveform samples are\n    // unsigned 8-bit PCM centered at 128. RMS gives short-term energy; an adaptive baseline\n    // follows song loudness, so a bounce fires on transients instead of a fixed timer.\n    val beatDetectorState = remember { floatArrayOf(0.035f) }\n    val lastBeatAtMs = remember { longArrayOf(0L) }\n    LaunchedEffect(visualizerWaveform, beatBounceAlbumArt, state.isPlaying) {\n        val waveform = visualizerWaveform\n        if (!beatBounceAlbumArt || !state.isPlaying || waveform == null || waveform.size < 32) {\n            return@LaunchedEffect\n        }\n\n        var squareSum = 0.0\n        var peak = 0f\n        waveform.forEach { sample ->\n            val centered = (((sample.toInt() and 0xFF) - 128) / 128f)\n            val absolute = kotlin.math.abs(centered)\n            squareSum += (centered * centered).toDouble()\n            if (absolute > peak) peak = absolute\n        }\n        val rms = kotlin.math.sqrt(squareSum / waveform.size).toFloat()\n        val baseline = beatDetectorState[0].coerceAtLeast(0.015f)\n        val threshold = maxOf(0.055f, baseline * 1.38f)\n        val now = SystemClock.elapsedRealtime()\n        val isTransientBeat = rms > threshold && peak > 0.25f && now - lastBeatAtMs[0] >= 170L\n\n        // Do not let a loud beat immediately drag the baseline up to itself. This keeps the\n        // detector sensitive to the next rhythmic transient while still adapting across songs.\n        val baselineSample = minOf(rms, baseline * 1.22f)\n        beatDetectorState[0] = baseline * 0.92f + baselineSample * 0.08f\n\n        if (isTransientBeat) {\n            lastBeatAtMs[0] = now\n            beatPulseSequence++\n        }\n    }\n'''
)

replace_once(
'''                                                rotationX = if (parallaxAlbumArt) parallaxPhase.value * 3.2f else 0f\n                                                rotationY = if (parallaxAlbumArt) -parallaxPhase.value * 5.2f else 0f''',
'''                                                rotationX = if (parallaxAlbumArt) sensorTiltY * 5.5f else 0f\n                                                rotationY = if (parallaxAlbumArt) -sensorTiltX * 7.5f else 0f\n                                                translationX = if (parallaxAlbumArt) sensorTiltX * 12f else 0f\n                                                translationY = if (parallaxAlbumArt) sensorTiltY * 8f else 0f'''
)

replace_once(
'''                                            rotationX = if (parallaxAlbumArt) parallaxPhase.value * 4.5f else 0f\n                                            rotationY = if (parallaxAlbumArt) -parallaxPhase.value * 7f else 0f''',
'''                                            rotationX = if (parallaxAlbumArt) sensorTiltY * 5.5f else 0f\n                                            rotationY = if (parallaxAlbumArt) -sensorTiltX * 7.5f else 0f\n                                            translationX = if (parallaxAlbumArt) sensorTiltX * 12f else 0f\n                                            translationY = if (parallaxAlbumArt) sensorTiltY * 8f else 0f'''
)

path.write_text(text)
print('Applied real sensor parallax and audio-reactive beat bounce.')
