from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def patch_file(rel, edits, import_line=None, import_after=None):
    path = ROOT / rel
    text = path.read_text()
    if import_line and import_line not in text:
        if not import_after or import_after not in text:
            raise SystemExit(f"Import anchor missing in {rel}: {import_after}")
        text = text.replace(import_after, import_after + "\n" + import_line, 1)
    for old, new in edits:
        if new in text:
            continue
        if old not in text:
            raise SystemExit(f"Patch anchor missing in {rel}: {old!r}")
        text = text.replace(old, new, 1)
    path.write_text(text)


patch_file(
    "app/src/main/java/com/wavelength/music/ui/home/HomeScreen.kt",
    [
        ("shape = RoundedCornerShape(8.dp),", "shape = RoundedCornerShape(UiDesignConfig.PLAYLIST_CARD_RADIUS_DP.dp),"),
        (".height(58.dp)\n            .clickable(onClick = onClick),", ".height(UiDesignConfig.QUICK_TILE_HEIGHT_DP.dp)\n            .clickable(onClick = onClick),"),
        ("shape = RoundedCornerShape(6.dp),", "shape = RoundedCornerShape(UiDesignConfig.QUICK_TILE_RADIUS_DP.dp),"),
        ("modifier = Modifier.size(58.dp)", "modifier = Modifier.size(UiDesignConfig.QUICK_TILE_HEIGHT_DP.dp)"),
    ],
    import_line="import com.wavelength.music.ui.design.UiDesignConfig",
    import_after="import com.wavelength.music.ui.components.TrackRow",
)

patch_file(
    "app/src/main/java/com/wavelength/music/ui/components/MiniPlayerBar.kt",
    [
        ("val shape = RoundedCornerShape(28.dp)", "val shape = RoundedCornerShape(UiDesignConfig.MINI_PLAYER_RADIUS_DP.dp)"),
        (".height(64.dp)\n            .clip(shape)", ".height(UiDesignConfig.MINI_PLAYER_HEIGHT_DP.dp)\n            .clip(shape)"),
        ("barModifier = barModifier.height(64.dp)", "barModifier = barModifier.height(UiDesignConfig.MINI_PLAYER_HEIGHT_DP.dp)"),
        (".padding(horizontal = 12.dp),", ".padding(horizontal = UiDesignConfig.MINI_PLAYER_HORIZONTAL_PADDING_DP.dp),"),
        ("horizontalArrangement = Arrangement.spacedBy(12.dp)", "horizontalArrangement = Arrangement.spacedBy(UiDesignConfig.MINI_PLAYER_ITEM_GAP_DP.dp)"),
        (".size(44.dp)\n                        .clip(RoundedCornerShape(6.dp))", ".size(UiDesignConfig.MINI_PLAYER_ART_SIZE_DP.dp)\n                        .clip(RoundedCornerShape(UiDesignConfig.MINI_PLAYER_ART_RADIUS_DP.dp))"),
    ],
    import_line="import com.wavelength.music.ui.design.UiDesignConfig",
    import_after="import com.wavelength.music.playback.PlaybackUiState",
)

config_dir = ROOT / "app/src/main/java/com/wavelength/music/ui/design"
config_dir.mkdir(parents=True, exist_ok=True)
config_path = config_dir / "UiDesignConfig.kt"
if not config_path.exists():
    config_path.write_text("""package com.wavelength.music.ui.design

/**
 * Generated by the AzMusic GitHub Pages UI Designer.
 * These values are deliberately limited to stable visual dimensions used by Compose.
 */
object UiDesignConfig {
    const val QUICK_TILE_HEIGHT_DP = 58f
    const val QUICK_TILE_RADIUS_DP = 6f
    const val PLAYLIST_CARD_RADIUS_DP = 8f

    const val MINI_PLAYER_HEIGHT_DP = 64f
    const val MINI_PLAYER_RADIUS_DP = 28f
    const val MINI_PLAYER_ART_SIZE_DP = 44f
    const val MINI_PLAYER_ART_RADIUS_DP = 6f
    const val MINI_PLAYER_HORIZONTAL_PADDING_DP = 12f
    const val MINI_PLAYER_ITEM_GAP_DP = 12f
}
""")

print("AzMusic UI Designer bindings applied.")
