package com.wavelength.music.ui.design

/** Generated by the AzMusic GitHub Pages UI Designer. */
object UiDesignConfig {
    const val QUICK_TILE_HEIGHT_DP = 58f
    const val QUICK_TILE_RADIUS_DP = 6f
    const val PLAYLIST_CARD_RADIUS_DP = 8f

    const val MINI_PLAYER_HEIGHT_DP = 64f
    const val MINI_PLAYER_RADIUS_DP = 28f
    const val MINI_PLAYER_ART_SIZE_DP = 44f
    const val MINI_PLAYER_ART_RADIUS_DP = 6f
    const val MINI_PLAYER_HORIZONTAL_PADDING_DP = 12f
    const val MINI_PLAYER_ITEM_GAP_DP = 12f

    const val GLASS_QUEUE_AREA_HEIGHT_DP = 214f
    const val GLASS_QUEUE_GAP_DP = 22f
    const val GLASS_QUEUE_CARD_WIDTH_DP = 82f
    const val GLASS_QUEUE_CARD_HEIGHT_DP = 176f
    const val GLASS_QUEUE_CARD_RADIUS_DP = 11f
    const val GLASS_QUEUE_ARC_DEPTH_DP = 58f
    const val GLASS_LOWER_PANEL_HEIGHT_DP = 356f
    const val GLASS_LOWER_PANEL_TOP_PADDING_DP = 40f
    const val GLASS_SEEK_HORIZONTAL_PADDING_DP = 18f
    const val GLASS_SEEK_STROKE_DP = 3.2f
    const val GLASS_SEEK_THUMB_RADIUS_DP = 7f
    const val GLASS_TRANSPORT_FRAME_WIDTH_DP = 322f
    const val GLASS_TRANSPORT_FRAME_HEIGHT_DP = 184f
    const val GLASS_TRANSPORT_BODY_WIDTH_DP = 288f
    const val GLASS_TRANSPORT_BODY_HEIGHT_DP = 140f
    const val GLASS_ORB_SIZE_DP = 56f
    const val GLASS_SIDE_CONTROL_SIZE_DP = 68f
    const val GLASS_PLAY_OUTER_SIZE_DP = 120f
    const val GLASS_PLAY_INNER_SIZE_DP = 94f

    // Normalized x,y anchor pairs edited directly in the browser Shape Editor.
    // Values are relative to the GenericShape bounds (0f..1f).
    val GLASS_LOWER_PANEL_SHAPE_POINTS = floatArrayOf(
        1.0000f, 0.1875f,
        1.0000f, 1.0000f,
        0.0000f, 1.0000f,
        0.0000f, 0.1875f,
        0.0000f, 0.1875f,
        0.0247f, 0.1296f,
        0.0964f, 0.0773f,
        0.2081f, 0.0358f,
        0.3488f, 0.0092f,
        0.5048f, 0.0000f,
        0.6607f, 0.0092f,
        0.8015f, 0.0358f,
        0.9131f, 0.0773f,
        0.9848f, 0.1296f,
        1.0000f, 0.1875f
    )

    // Fine-polished symmetric Saturn/liquid contour. The denser shoulder points keep
    // the center ring round while the side pods flow into it without sharp kinks.
    val GLASS_TRANSPORT_SHAPE_POINTS = floatArrayOf(
        0.5000f, 0.0000f,
        0.5760f, 0.0180f,
        0.6360f, 0.0700f,
        0.6770f, 0.1540f,
        0.6990f, 0.2240f,
        0.7480f, 0.2380f,
        0.8080f, 0.2240f,
        0.8700f, 0.2450f,
        0.9270f, 0.3000f,
        0.9700f, 0.3800f,
        0.9950f, 0.4700f,
        1.0000f, 0.5350f,
        0.9840f, 0.6200f,
        0.9440f, 0.6900f,
        0.8860f, 0.7350f,
        0.8200f, 0.7580f,
        0.7600f, 0.7550f,
        0.7080f, 0.7900f,
        0.6740f, 0.8560f,
        0.6380f, 0.9280f,
        0.5780f, 0.9800f,
        0.5000f, 1.0000f,
        0.4220f, 0.9800f,
        0.3620f, 0.9280f,
        0.3260f, 0.8560f,
        0.2920f, 0.7900f,
        0.2400f, 0.7550f,
        0.1800f, 0.7580f,
        0.1140f, 0.7350f,
        0.0560f, 0.6900f,
        0.0160f, 0.6200f,
        0.0000f, 0.5350f,
        0.0050f, 0.4700f,
        0.0300f, 0.3800f,
        0.0730f, 0.3000f,
        0.1300f, 0.2450f,
        0.1920f, 0.2240f,
        0.2520f, 0.2380f,
        0.3010f, 0.2240f,
        0.3230f, 0.1540f,
        0.3640f, 0.0700f,
        0.4240f, 0.0180f
    )
}
