package com.wavelength.music.ui.design

/** Generated by the AzMusic GitHub Pages UI Designer. */
object UiDesignConfig {
    const val QUICK_TILE_HEIGHT_DP = 58f
    const val QUICK_TILE_RADIUS_DP = 6f
    const val PLAYLIST_CARD_RADIUS_DP = 8f

    const val MINI_PLAYER_HEIGHT_DP = 64f
    const val MINI_PLAYER_RADIUS_DP = 28f
    const val MINI_PLAYER_ART_SIZE_DP = 44f
    const val MINI_PLAYER_ART_RADIUS_DP = 6f
    const val MINI_PLAYER_HORIZONTAL_PADDING_DP = 12f
    const val MINI_PLAYER_ITEM_GAP_DP = 12f

    const val GLASS_QUEUE_AREA_HEIGHT_DP = 214f
    const val GLASS_QUEUE_GAP_DP = 22f
    const val GLASS_QUEUE_CARD_WIDTH_DP = 82f
    const val GLASS_QUEUE_CARD_HEIGHT_DP = 176f
    const val GLASS_QUEUE_CARD_RADIUS_DP = 11f
    const val GLASS_QUEUE_ARC_DEPTH_DP = 58f
    const val GLASS_LOWER_PANEL_HEIGHT_DP = 356f
    const val GLASS_LOWER_PANEL_TOP_PADDING_DP = 40f
    const val GLASS_SEEK_HORIZONTAL_PADDING_DP = 18f
    const val GLASS_SEEK_STROKE_DP = 3.2f
    const val GLASS_SEEK_THUMB_RADIUS_DP = 7f
    const val GLASS_TRANSPORT_FRAME_WIDTH_DP = 322f
    const val GLASS_TRANSPORT_FRAME_HEIGHT_DP = 184f
    const val GLASS_TRANSPORT_BODY_WIDTH_DP = 292f
    const val GLASS_TRANSPORT_BODY_HEIGHT_DP = 142f
    const val GLASS_ORB_SIZE_DP = 56f
    const val GLASS_SIDE_CONTROL_SIZE_DP = 68f
    const val GLASS_PLAY_OUTER_SIZE_DP = 120f
    const val GLASS_PLAY_INNER_SIZE_DP = 94f
}
