package com.wavelength.music.ui.design

/** Generated by the AzMusic GitHub Pages UI Designer. */
object UiDesignConfig {
    const val QUICK_TILE_HEIGHT_DP = 58f
    const val QUICK_TILE_RADIUS_DP = 6f
    const val PLAYLIST_CARD_RADIUS_DP = 8f

    const val MINI_PLAYER_HEIGHT_DP = 64f
    const val MINI_PLAYER_RADIUS_DP = 28f
    const val MINI_PLAYER_ART_SIZE_DP = 44f
    const val MINI_PLAYER_ART_RADIUS_DP = 6f
    const val MINI_PLAYER_HORIZONTAL_PADDING_DP = 12f
    const val MINI_PLAYER_ITEM_GAP_DP = 12f

    const val GLASS_QUEUE_AREA_HEIGHT_DP = 214f
    const val GLASS_QUEUE_GAP_DP = 22f
    const val GLASS_QUEUE_CARD_WIDTH_DP = 82f
    const val GLASS_QUEUE_CARD_HEIGHT_DP = 176f
    const val GLASS_QUEUE_CARD_RADIUS_DP = 11f
    const val GLASS_QUEUE_ARC_DEPTH_DP = 58f
    const val GLASS_LOWER_PANEL_HEIGHT_DP = 356f
    const val GLASS_LOWER_PANEL_TOP_PADDING_DP = 40f
    const val GLASS_SEEK_HORIZONTAL_PADDING_DP = 18f
    const val GLASS_SEEK_STROKE_DP = 3.2f
    const val GLASS_SEEK_THUMB_RADIUS_DP = 7f
    const val GLASS_TRANSPORT_FRAME_WIDTH_DP = 322f
    const val GLASS_TRANSPORT_FRAME_HEIGHT_DP = 184f
    const val GLASS_TRANSPORT_BODY_WIDTH_DP = 292f
    const val GLASS_TRANSPORT_BODY_HEIGHT_DP = 142f
    const val GLASS_ORB_SIZE_DP = 56f
    const val GLASS_SIDE_CONTROL_SIZE_DP = 68f
    const val GLASS_PLAY_OUTER_SIZE_DP = 120f
    const val GLASS_PLAY_INNER_SIZE_DP = 94f

    // Normalized x,y anchor pairs edited directly in the browser Shape Editor.
    // Values are relative to the GenericShape bounds (0f..1f).
    val GLASS_LOWER_PANEL_SHAPE_POINTS = floatArrayOf(
        1.0000f, 0.1875f,
        1.0000f, 1.0000f,
        0.0000f, 1.0000f,
        0.0000f, 0.1875f,
        0.0000f, 0.1875f,
        0.0247f, 0.1296f,
        0.0964f, 0.0773f,
        0.2081f, 0.0358f,
        0.3488f, 0.0092f,
        0.5048f, 0.0000f,
        0.6607f, 0.0092f,
        0.8015f, 0.0358f,
        0.9131f, 0.0773f,
        0.9848f, 0.1296f,
        1.0000f, 0.1875f
    )

    val GLASS_TRANSPORT_SHAPE_POINTS = floatArrayOf(
        0.6592f, 0.9045f,
        0.5802f, 0.9755f,
        0.4925f, 1.0000f,
        0.4049f, 0.9755f,
        0.3259f, 0.9045f,
        0.2848f, 0.8321f,
        0.2166f, 0.8184f,
        0.1292f, 0.7750f,
        0.0599f, 0.7074f,
        0.0153f, 0.6222f,
        0.0000f, 0.5278f,
        0.0153f, 0.4334f,
        0.0599f, 0.3482f,
        0.1292f, 0.2806f,
        0.2166f, 0.2372f,
        0.2570f, 0.2272f,
        0.2631f, 0.2061f,
        0.3259f, 0.0955f,
        0.4049f, 0.0245f,
        0.4925f, 0.0000f,
        0.5802f, 0.0245f,
        0.6592f, 0.0955f,
        0.7177f, 0.1959f,
        0.7834f, 0.2094f,
        0.8708f, 0.2528f,
        0.9401f, 0.3204f,
        0.9847f, 0.4056f,
        1.0000f, 0.5000f,
        0.9847f, 0.5944f,
        0.9401f, 0.6796f,
        0.8708f, 0.7472f,
        0.7834f, 0.7906f,
        0.7177f, 0.8041f
    )
}